DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'enum_project_records_media_type'
  ) THEN
    CREATE TYPE enum_project_records_media_type AS ENUM ('image', 'video', 'external', 'documentation');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS project_records (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar NOT NULL,
  slug varchar NOT NULL,
  description varchar NOT NULL,
  date timestamptz NULL,
  updated timestamptz NULL,
  status varchar NULL,
  featured boolean NOT NULL DEFAULT false,
  featured_order numeric NOT NULL DEFAULT 0,
  featured_image varchar NULL,
  github_url varchar NULL,
  live_url varchar NULL,
  app_url varchar NULL,
  app_label varchar NULL,
  published boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE project_records ADD COLUMN IF NOT EXISTS title varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS slug varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS description varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS date timestamptz;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS updated timestamptz;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS status varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS featured boolean NOT NULL DEFAULT false;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS featured_order numeric NOT NULL DEFAULT 0;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS featured_image varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS github_url varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS live_url varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS app_url varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS app_label varchar;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS published boolean NOT NULL DEFAULT true;
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE project_records ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS project_records_slug_idx ON project_records (slug);
CREATE INDEX IF NOT EXISTS project_records_featured_order_idx ON project_records (featured_order);
CREATE INDEX IF NOT EXISTS project_records_published_idx ON project_records (published);
CREATE INDEX IF NOT EXISTS project_records_featured_idx ON project_records (featured);
CREATE INDEX IF NOT EXISTS project_records_date_idx ON project_records (date);
CREATE INDEX IF NOT EXISTS project_records_updated_idx ON project_records (updated);

CREATE TABLE IF NOT EXISTS project_records_tags (
  _order integer NOT NULL,
  _parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  id varchar PRIMARY KEY,
  tag varchar NOT NULL
);

CREATE INDEX IF NOT EXISTS project_records_tags_parent_idx ON project_records_tags (_parent_id, _order);

CREATE TABLE IF NOT EXISTS project_records_images (
  _order integer NOT NULL,
  _parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  id varchar PRIMARY KEY,
  image varchar NOT NULL
);

CREATE INDEX IF NOT EXISTS project_records_images_parent_idx ON project_records_images (_parent_id, _order);

CREATE TABLE IF NOT EXISTS project_records_app_links (
  _order integer NOT NULL,
  _parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  id varchar PRIMARY KEY,
  label varchar NOT NULL,
  href varchar NOT NULL,
  description varchar NULL,
  kind varchar NULL,
  external boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS project_records_app_links_parent_idx ON project_records_app_links (_parent_id, _order);

CREATE TABLE IF NOT EXISTS project_records_links (
  _order integer NOT NULL,
  _parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  id varchar PRIMARY KEY,
  label varchar NOT NULL,
  href varchar NOT NULL,
  description varchar NULL,
  kind varchar NULL,
  external boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS project_records_links_parent_idx ON project_records_links (_parent_id, _order);

CREATE TABLE IF NOT EXISTS project_records_search_keywords (
  _order integer NOT NULL,
  _parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  id varchar PRIMARY KEY,
  keyword varchar NOT NULL
);

CREATE INDEX IF NOT EXISTS project_records_search_keywords_parent_idx ON project_records_search_keywords (_parent_id, _order);

CREATE TABLE IF NOT EXISTS project_records_media (
  _order integer NOT NULL,
  _parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  id varchar PRIMARY KEY,
  type enum_project_records_media_type NOT NULL,
  src varchar NULL,
  url varchar NULL,
  title varchar NULL,
  thumbnail varchar NULL
);

CREATE INDEX IF NOT EXISTS project_records_media_parent_idx ON project_records_media (_parent_id, _order);

CREATE TABLE IF NOT EXISTS project_records_rels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order" integer NULL,
  parent_id integer NOT NULL REFERENCES project_records(id) ON DELETE CASCADE,
  path varchar NOT NULL,
  site_download_assets_id integer NULL REFERENCES site_download_assets(id)
);

CREATE INDEX IF NOT EXISTS project_records_rels_parent_idx ON project_records_rels (parent_id, path);

CREATE TABLE IF NOT EXISTS resume_records (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar NOT NULL,
  slug varchar NOT NULL,
  file_name varchar NOT NULL,
  role varchar NOT NULL,
  summary varchar NOT NULL,
  featured_order numeric NOT NULL DEFAULT 0,
  published boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS title varchar;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS slug varchar;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS file_name varchar;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS role varchar;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS summary varchar;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS featured_order numeric NOT NULL DEFAULT 0;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS published boolean NOT NULL DEFAULT true;
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE resume_records ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS resume_records_slug_idx ON resume_records (slug);
CREATE INDEX IF NOT EXISTS resume_records_featured_order_idx ON resume_records (featured_order);
CREATE INDEX IF NOT EXISTS resume_records_published_idx ON resume_records (published);

CREATE TABLE IF NOT EXISTS resume_records_rels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order" integer NULL,
  parent_id integer NOT NULL REFERENCES resume_records(id) ON DELETE CASCADE,
  path varchar NOT NULL,
  site_download_assets_id integer NULL REFERENCES site_download_assets(id)
);

CREATE INDEX IF NOT EXISTS resume_records_rels_parent_idx ON resume_records_rels (parent_id, path);

ALTER TABLE payload_locked_documents_rels
  ADD COLUMN IF NOT EXISTS project_records_id integer,
  ADD COLUMN IF NOT EXISTS resume_records_id integer;

ALTER TABLE payload_preferences_rels
  ADD COLUMN IF NOT EXISTS project_records_id integer,
  ADD COLUMN IF NOT EXISTS resume_records_id integer;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar_url varchar;
