import fs from 'fs';
import path from 'path';

export interface BookEntry {
  slug: string;
  title: string;
  description?: string;
  hasRepub: boolean;
  hasEpub: boolean;
}

let cached: BookEntry[] | null = null;

/**
 * List of books from build-time manifest (public/books/manifest.json).
 * Generated by `pnpm run build:books` from repo-root books/.
 */
export function getBooks(): BookEntry[] {
  if (cached) return cached;
  const manifestPath = path.join(process.cwd(), 'public', 'books', 'manifest.json');
  try {
    const raw = fs.readFileSync(manifestPath, 'utf-8');
    cached = JSON.parse(raw) as BookEntry[];
    return cached;
  } catch {
    return [];
  }
}

export function getBookBySlug(slug: string): BookEntry | undefined {
  return getBooks().find((b) => b.slug === slug);
}
