import fs from 'fs';
import path from 'path';

export interface BookEntry {
  slug: string;
  title: string;
  description?: string;
  hasEpub: boolean;
}

let cached: BookEntry[] | null = null;

function resolveManifestPath() {
  const candidates = [
    path.join(process.cwd(), 'public', 'books', 'manifest.json'),
    path.join(process.cwd(), 'apps', 'portfolio', 'public', 'books', 'manifest.json'),
  ];

  return candidates.find((candidate) => fs.existsSync(candidate));
}

/**
 * List of books from **autogenerated** `public/books/manifest.json`.
 * Produced by `pnpm run build:books` (repo root) and refreshed during **`pnpm dev`**
 * by `scripts/watch-books-dev.cjs` when `books/**` changes. Do not edit the JSON by hand.
 */
export function getBooks(): BookEntry[] {
  if (process.env.NODE_ENV === 'production' && cached) return cached;
  const manifestPath = resolveManifestPath();
  if (!manifestPath) {
    return [];
  }

  try {
    const raw = fs.readFileSync(manifestPath, 'utf-8');
    const list = JSON.parse(raw) as BookEntry[];
    if (process.env.NODE_ENV === 'production') cached = list;
    return list;
  } catch {
    return [];
  }
}

export function getBookBySlug(slug: string): BookEntry | undefined {
  return getBooks().find((b) => b.slug === slug);
}
