import fs from 'fs';
import path from 'path';

export interface BookEntry {
  slug: string;
  title: string;
  description?: string;
  hasEpub: boolean;
}

let cached: BookEntry[] | null = null;

function resolveManifestPath() {
  const candidates = [
    path.join(process.cwd(), 'public', 'books', 'manifest.json'),
    path.join(process.cwd(), 'apps', 'portfolio', 'public', 'books', 'manifest.json'),
  ];

  return candidates.find((candidate) => fs.existsSync(candidate));
}

/**
 * List of books from build-time manifest (public/books/manifest.json).
 * Generated by `pnpm run build:books` from repo-root books/.
 */
export function getBooks(): BookEntry[] {
  if (cached) return cached;
  const manifestPath = resolveManifestPath();
  if (!manifestPath) {
    return [];
  }

  try {
    const raw = fs.readFileSync(manifestPath, 'utf-8');
    cached = JSON.parse(raw) as BookEntry[];
    return cached;
  } catch {
    return [];
  }
}

export function getBookBySlug(slug: string): BookEntry | undefined {
  return getBooks().find((b) => b.slug === slug);
}
