import fs from 'node:fs'
import { spawn } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)
const repoRoot = path.resolve(dirname, '..')
const grimeTimeRoot = path.join(repoRoot, 'vendor', 'grime-time-site')
const grimeTimeEnvPath = path.join(grimeTimeRoot, '.env')

const command = process.argv[2] || 'help'
const force = process.argv.includes('--force')

const SYSTEM_ENV_KEYS = [
  'APPDATA',
  'CI',
  'COMSPEC',
  'FORCE_COLOR',
  'HOME',
  'HOMEDRIVE',
  'HOMEPATH',
  'LOCALAPPDATA',
  'NUMBER_OF_PROCESSORS',
  'OS',
  'PATH',
  'PATHEXT',
  'PROCESSOR_ARCHITECTURE',
  'PROCESSOR_IDENTIFIER',
  'PROCESSOR_LEVEL',
  'PROCESSOR_REVISION',
  'PROGRAMDATA',
  'PROGRAMFILES',
  'PROGRAMFILES(X86)',
  'SYSTEMDRIVE',
  'SYSTEMROOT',
  'TEMP',
  'TERM',
  'TMP',
  'USERPROFILE',
  'WINDIR',
]

const LOCAL_ENV_TEMPLATE = `# Local vendor bootstrap for Grime Time
# Generated by scripts/grimetime-vendor.mjs

# Required for local build + runtime shell
# Example local Docker/compose URL: postgresql://postgres@127.0.0.1:54320/grimetime
POSTGRES_URL=
PAYLOAD_SECRET=grimetime-local-payload-secret
NEXT_PUBLIC_SERVER_URL=http://localhost:5465
CRON_SECRET=grimetime-local-cron-secret
PREVIEW_SECRET=grimetime-local-preview-secret

# Local admin bootstrap
ADMIN_EMAIL=owner@grimetime.local
ADMIN_PASSWORD=changethis
ADMIN_NAME=Grime Time Owner

# Optional alternate seed login
SEED_LOGIN_EMAIL=
SEED_LOGIN_PASSWORD=

# Portal defaults
PORTAL_ADMIN_ONLY=false
PORTAL_PREVIEW_TEST_USER_EMAIL=test_user@grimetime.app
QUOTES_INTERNAL_ENABLED=true
QUOTES_INTERNAL_EMAILS=bg@grimetime.local,pb@grimetime.local,de@grimetime.local

# Optional Supabase auth / storage
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
PAYLOAD_OAUTH_ALLOWED_EMAILS=
SUPABASE_URL=
SUPABASE_STORAGE_BUCKET=media
SUPABASE_S3_ACCESS_KEY_ID=
SUPABASE_S3_SECRET_ACCESS_KEY=
SUPABASE_S3_ENDPOINT=
SUPABASE_S3_REGION=us-east-1

# Optional email delivery
RESEND_API_KEY=
EMAIL_FROM=
EMAIL_FROM_NAME=Grime Time

# Optional Stripe billing
STRIPE_SECRET_KEY=
STRIPE_ACCOUNT_ID=
STRIPE_WEBHOOK_SECRET=

# Optional Payload MCP
PAYLOAD_MCP_ENABLED=false
PAYLOAD_MCP_VERBOSE_LOGS=false
PAYLOAD_MCP_SERVER_NAME=Grime Time Payload MCP
PAYLOAD_MCP_API_KEY=
PAYLOAD_MCP_URL=http://localhost:5465/api/mcp

# Optional image generation
IMAGE_GEN_MCP_ENABLED=false
OPENAI_API_KEY=
OPENAI_IMAGE_MODEL=gpt-image-1
PROVIDERS__OPENAI__API_KEY=
PROVIDERS__OPENAI__BASE_URL=https://api.openai.com/v1
PROVIDERS__OPENAI__ORGANIZATION=
PROVIDERS__OPENAI__TIMEOUT=300.0
PROVIDERS__OPENAI__MAX_RETRIES=3
PROVIDERS__OPENAI__ENABLED=false

PROVIDERS__GEMINI__API_KEY=
PROVIDERS__GEMINI__BASE_URL=https://us-central1-aiplatform.googleapis.com/v1
PROVIDERS__GEMINI__TIMEOUT=300.0
PROVIDERS__GEMINI__MAX_RETRIES=3
PROVIDERS__GEMINI__ENABLED=false
PROVIDERS__GEMINI__DEFAULT_MODEL=imagen-4

IMAGES__DEFAULT_MODEL=gpt-image-1
IMAGES__DEFAULT_QUALITY=auto
IMAGES__DEFAULT_SIZE=1536x1024
IMAGES__DEFAULT_STYLE=vivid
IMAGES__DEFAULT_MODERATION=auto
IMAGES__DEFAULT_OUTPUT_FORMAT=png
IMAGES__BASE_HOST=

SERVER__NAME=Image Gen MCP Server
SERVER__VERSION=0.1.0
SERVER__PORT=3001
SERVER__HOST=127.0.0.1
SERVER__LOG_LEVEL=INFO
SERVER__RATE_LIMIT_RPM=50

STORAGE__BASE_PATH=./storage
STORAGE__RETENTION_DAYS=30
STORAGE__MAX_SIZE_GB=10.0
STORAGE__CLEANUP_INTERVAL_HOURS=24

CACHE__ENABLED=true
CACHE__TTL_HOURS=24
CACHE__BACKEND=memory
CACHE__MAX_SIZE_MB=500
CACHE__REDIS_URL=
`

function ensureVendorExists() {
  if (!fs.existsSync(grimeTimeRoot)) {
    throw new Error(
      'vendor/grime-time-site is missing. Run `pnpm run vendor:grimetime:init` first.',
    )
  }
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return new Map()
  }

  const map = new Map()
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/)

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) {
      continue
    }

    const separator = trimmed.indexOf('=')
    if (separator === -1) {
      continue
    }

    const key = trimmed.slice(0, separator).trim()
    const value = trimmed.slice(separator + 1).trim()
    map.set(key, value)
  }

  return map
}

function pickSystemEnv() {
  const env = {}
  const processEnvEntries = Object.entries(process.env)

  function findEnvValue(targetKey) {
    const normalizedTarget = targetKey.toUpperCase()

    for (const [key, value] of processEnvEntries) {
      if (key.toUpperCase() === normalizedTarget) {
        return { key, value }
      }
    }

    return null
  }

  for (const key of SYSTEM_ENV_KEYS) {
    const match = findEnvValue(key)
    if (match?.value !== undefined) {
      env[match.key] = match.value
    }
  }

  return env
}

function buildVendorEnv(overrides = {}) {
  ensureVendorExists()
  const envMap = parseEnvFile(grimeTimeEnvPath)
  const vendorEnv = Object.fromEntries(envMap.entries())

  return {
    ...pickSystemEnv(),
    ...vendorEnv,
    ...overrides,
  }
}

function getNpmCommand() {
  return process.platform === 'win32' ? 'npm.cmd' : 'npm'
}

function quoteWindowsArg(value) {
  if (!/[ \t"&()]/.test(value)) {
    return value
  }

  return `"${value.replace(/"/g, '\\"')}"`
}

function splitExtraArgs(args) {
  const separatorIndex = args.indexOf('--')

  if (separatorIndex === -1) {
    return { head: args, tail: [] }
  }

  return {
    head: args.slice(0, separatorIndex),
    tail: args.slice(separatorIndex + 1),
  }
}

function parseRunArgs(args) {
  const { head, tail } = splitExtraArgs(args)
  const envOverrides = {}
  const positional = []

  for (let index = 0; index < head.length; index += 1) {
    const token = head[index]

    if (token === '--env') {
      const pair = head[index + 1]
      if (!pair || !pair.includes('=')) {
        throw new Error('Expected KEY=VALUE after --env')
      }

      const separator = pair.indexOf('=')
      envOverrides[pair.slice(0, separator)] = pair.slice(separator + 1)
      index += 1
      continue
    }

    positional.push(token)
  }

  return {
    envOverrides,
    positional,
    extraArgs: tail,
  }
}

function spawnInVendor(args, envOverrides = {}) {
  const env = buildVendorEnv(envOverrides)
  const child =
    process.platform === 'win32'
      ? spawn(process.env.ComSpec || 'cmd.exe', ['/d', '/s', '/c', [getNpmCommand(), ...args].map(quoteWindowsArg).join(' ')], {
          cwd: grimeTimeRoot,
          env,
          stdio: 'inherit',
        })
      : spawn(getNpmCommand(), args, {
          cwd: grimeTimeRoot,
          env,
          stdio: 'inherit',
        })

  child.on('exit', (code) => process.exit(code ?? 0))
  child.on('error', (error) => {
    console.error(error instanceof Error ? error.message : error)
    process.exit(1)
  })
}

function writeLocalEnv() {
  ensureVendorExists()

  if (fs.existsSync(grimeTimeEnvPath) && !force) {
    console.log(`[grimetime-vendor] ${path.relative(repoRoot, grimeTimeEnvPath)} already exists. Use --force to replace it.`)
    return
  }

  fs.writeFileSync(grimeTimeEnvPath, LOCAL_ENV_TEMPLATE, 'utf8')
  console.log(`[grimetime-vendor] wrote ${path.relative(repoRoot, grimeTimeEnvPath)}`)
  console.log('[grimetime-vendor] POSTGRES_URL is intentionally blank so build-only validation can run without touching a database.')
}

function installVendor() {
  ensureVendorExists()
  spawnInVendor(['install'])
}

function runVendorScript(args) {
  const { positional, extraArgs, envOverrides } = parseRunArgs(args)
  const scriptName = positional[0]

  if (!scriptName) {
    throw new Error('run-script requires a script name, e.g. `run-script dev`')
  }

  const npmArgs = ['run', scriptName]

  if (extraArgs.length > 0) {
    npmArgs.push('--', ...extraArgs)
  }

  console.log(
    `[grimetime-vendor] npm ${npmArgs.join(' ')} (cwd=vendor/grime-time-site, env=vendor/grime-time-site/.env)`,
  )
  spawnInVendor(npmArgs, envOverrides)
}

function checkLocalEnv() {
  ensureVendorExists()

  const env = parseEnvFile(grimeTimeEnvPath)
  const requiredForShell = [
    'PAYLOAD_SECRET',
    'NEXT_PUBLIC_SERVER_URL',
    'CRON_SECRET',
    'PREVIEW_SECRET',
  ]
  const requiredForCurrentRuntime = ['POSTGRES_URL', 'ADMIN_EMAIL', 'ADMIN_PASSWORD']
  const optionalIntegrations = [
    'NEXT_PUBLIC_SUPABASE_URL',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    'SUPABASE_URL',
    'SUPABASE_S3_ACCESS_KEY_ID',
    'SUPABASE_S3_SECRET_ACCESS_KEY',
    'RESEND_API_KEY',
    'EMAIL_FROM',
    'STRIPE_SECRET_KEY',
    'PROVIDERS__OPENAI__API_KEY',
  ]

  if (!fs.existsSync(grimeTimeEnvPath)) {
    console.log('[grimetime-vendor] missing vendor/grime-time-site/.env')
    console.log('[grimetime-vendor] run `pnpm run vendor:grimetime:env` to scaffold a local env file.')
    process.exit(1)
  }

  console.log('[grimetime-vendor] env status')

  for (const key of requiredForShell) {
    const value = env.get(key)
    console.log(`- ${key}: ${value ? 'set' : 'missing'} (needed for local shell wiring)`)
  }

  for (const key of requiredForCurrentRuntime) {
    const value = env.get(key)
    console.log(`- ${key}: ${value ? 'set' : 'missing'} (needed for current build/dev/admin runtime)`)
  }

  for (const key of optionalIntegrations) {
    const value = env.get(key)
    console.log(`- ${key}: ${value ? 'set' : 'blank'} (optional integration)`)
  }

  const postgresUrl = env.get('POSTGRES_URL')
  if (!postgresUrl) {
    console.log('[grimetime-vendor] POSTGRES_URL is blank. Current Grime Time main still touches Payload during prerender, so build/dev/admin all need a reachable Postgres database.')
  }
}

function printHelp() {
  console.log('Usage: node scripts/grimetime-vendor.mjs <command>')
  console.log('')
  console.log('Commands:')
  console.log('  env [--force]  Create vendor/grime-time-site/.env with safe local defaults')
  console.log('  check          Print local env readiness for stub build vs full admin runtime')
  console.log('  install        Run npm install inside vendor/grime-time-site with isolated env')
  console.log('  run-script     Run an npm script inside vendor/grime-time-site with isolated env')
  console.log('                 Example: node scripts/grimetime-vendor.mjs run-script dev --env GT_DEV_PORT=5465')
}

switch (command) {
  case 'env':
    writeLocalEnv()
    break
  case 'check':
    checkLocalEnv()
    break
  case 'install':
    installVendor()
    break
  case 'run-script':
    runVendorScript(process.argv.slice(3))
    break
  default:
    printHelp()
    break
}
